### ISSUE TITLE
Message Text Table is too long - No Rom generated

### ISSUE THREAD

**Issue by TreZc0** [AmazingAmpharos/OoT-Randomizer#217]
Apparently, you can overflow the text by using multiple settings that influence texts in the game.
This combination seems legit, but cannot be generated.

`--tokensanity all --logic_tricks --enhance_map_compass --shuffle_mapcompass keysanity --shuffle_smallkeys keysanity --shuffle_bosskeys keysanity --shopsanity 4` 

is already enough to cause the error, in this case:
` Traceback (most recent call last):
  File "OoTRandomizer.py", line 62, in <module>
  File "OoTRandomizer.py", line 59, in start
  File "Main.py", line 137, in main
  File "Patches.py", line 1532, in patch_rom
  File "Messages.py", line 745, in repack_messages
TypeError: Message Text table is too large: 0x381b4 written / 0x38130 allowed.
[16475] Failed to execute script OoTRandomizer
`
The Issue mostly seems to be related to the --enhance_map_compass setting.

**Comment by flagrama** [comment]
https://github.com/TestRunnerSRL/OoT-Randomizer/issues/238

Is this still an issue on dev after this? Or only on 3.0?
